{
 "title": "Krakend Messaging",
 "description": "Metrics for async agents and pubsub backends",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" },
   { "name": "kind", "label": "Broker Kind", "query": { "query": "label_values(messaging_kind)" } },
   { "name": "topic", "label": "Topic", "query": { "query": "label_values(messaging_topic)" } }
  ]
 },
 "panels": [
  {
   "title": "Subscriber Avg Latency",
   "type": "timeseries",
   "description": "Average response latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(messaging_read_body_duration_seconds_sum{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"subscriber\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_read_body_duration_seconds_count{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Subscriber Avg Size",
   "type": "timeseries",
   "description": "Average body size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(messaging_read_body_size_bytes_sum{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"subscriber\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_read_body_size_bytes_count{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Subscriber Read Duration",
   "type": "heatmap",
   "description": "Histogram showing time spent reading on a subscriber backend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(messaging_read_body_duration_seconds_bucket{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"subscriber\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriber Read Size",
   "type": "heatmap",
   "description": "Histogram showing body size read on subscriber backends.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(messaging_read_body_size_bytes_bucket{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"subscriber\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writer Avg Latency",
   "type": "timeseries",
   "description": "Average message writing latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(messaging_write_body_duration_seconds_sum{app=~\"$app\", instance=~\"$instance\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_write_body_duration_seconds_count{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Writer Avg Size",
   "type": "timeseries",
   "description": "Average body size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(messaging_write_body_size_bytes_sum{app=~\"$app\", instance=~\"$instance\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_write_body_size_bytes_count{app=~\"$app\", instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Publisher Write Duration",
   "type": "heatmap",
   "description": "Histogram showing time spent writting on a publisher backend.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(messaging_write_body_duration_seconds_bucket{app=~\"$app\", instance=~\"$instance\", messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publisher Write Size",
   "type": "heatmap",
   "description": "Histogram showing the body size written on a publisher backend.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(messaging_write_body_size_bytes_bucket{app=~\"$app\", instance=~\"$instance\", messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Agent Read Avg Latency",
   "type": "timeseries",
   "description": "Average read latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(messaging_read_body_duration_seconds_sum{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_read_body_duration_seconds_count{app=~\"$app\", instance=~\"$instance\",  messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Async Agent Read Avg Size",
   "type": "timeseries",
   "description": "Average body size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(messaging_read_body_size_bytes_sum{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval]) / rate(messaging_read_body_size_bytes_count{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$interval])",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Async Agent Read Duration",
   "type": "heatmap",
   "description": "Histogram showing time spent reading on async agent.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(messaging_read_body_duration_seconds_bucket{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Agent Read Size",
   "type": "heatmap",
   "description": "Histogram showing body size read on async agents.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(messaging_read_body_size_bytes_bucket{app=~\"$app\", instance=~\"$instance\", messaging_origin=\"asyncagent\",messaging_kind=~\"$kind\", messaging_topic=\"$topic\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}