{
 "title": "KrakenD Websockets",
 "description": "Metrics collected from websockets",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  { "title": "Websocket Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(websocket_server_connections_count_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Connections"
    },
    {
     "expr": "-rate(websocket_server_disconnections_count_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Disconnections"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "websocket_server_connections_count_total-websocket_server_disconnections_count_total",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Ingressing Messages Size (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(websocket_server_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(websocket_server_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(websocket_server_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(websocket_server_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(websocket_server_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Egressing Messages Size (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(websocket_server_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(websocket_server_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(websocket_server_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(websocket_server_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(websocket_server_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Ingressing/Egressing Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(websocket_server_request_size_hist_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Ingressing"
    },
    {
     "expr": "-rate(websocket_server_response_size_hist_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Egressing"
    }
   ]
  },
  {
   "title": "Ingressing/Egressing Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(websocket_server_request_size_hist_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Ingressing"
    },
    {
     "expr": "-rate(websocket_server_response_size_hist_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Egressing"
    }
   ]
  },
  { "title": "Websocket Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Connection Events Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(websocket_client_connections_count_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Connections"
    },
    {
     "expr": "-rate(websocket_client_disconnections_count_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Disconnections"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "websocket_client_connections_count_total-websocket_client_disconnections_count_total",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Ingressing Messages Size (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(websocket_client_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(websocket_client_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(websocket_client_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(websocket_client_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(websocket_client_response_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Egressing Messages Size (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(websocket_client_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(websocket_client_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(websocket_client_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(websocket_client_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(websocket_client_request_size_hist_bucket{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Ingressing/Egressing Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(websocket_client_response_size_hist_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Ingressing"
    },
    {
     "expr": "-rate(websocket_client_request_size_hist_count{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Egressing"
    }
   ]
  },
  {
   "title": "Ingressing/Egressing Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(websocket_client_response_size_hist_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Ingressing"
    },
    {
     "expr": "-rate(websocket_client_request_size_hist_sum{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Egressing"
    }
   ]
  }
 ]
}