{
 "title": "KrakenD (InfluxDB v2)",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"krakend\", tag: \"host\")"
   },
   {
    "name": "resolution",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_INFLUX", "query": "InfluxDB" }
  ]
 },
 "panels": [
  {
   "title": "Router Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router\" and r._field == \"gauge\" and r.direction == \"in\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"pipe\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "layer", "operator": "=", "value": "pipe" }
     ]
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"backend\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "layer", "operator": "=", "value": "backend" }
     ]
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"mean\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Std dev Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"stddev\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "stddev" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"max\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: max)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Allocated Mem (per host)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.Alloc\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "MemStats.Alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Go routines per host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"NumGoroutine\")\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "NumGoroutine" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Throughput (per $resolution)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"responses\" and r._field == \"count\" and r.host =~ /${host}/)\n    |> group(columns: [\"name\",\"status\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Endpoint Response Time (per $resolution)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"mean\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Connections (per $resolution)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router\" and r._field == \"gauge\" and r.direction == \"in\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "direction", "operator": "=", "value": "in" }
     ]
    }
   ]
  },
  {
   "title": "Response Distribution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "responses",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"responses\" and r._field == \"count\" and r.host =~ /${host}/)\n    |> group(columns: [\"status\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"mean\"  and r.host =~ /${host}/)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-time",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-time\" and r._field == \"mean\" and r.host =~ /${host}/)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.response-size",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-size\" and r._field == \"mean\" and r.host =~ /${host}/)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Size HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "router.response-size",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router.response-size\" and r._field == \"mean\" and r.host =~ /${host}/)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Router connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "open",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"router\" and r._field == \"total\" and r.direction == \"in\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction", "operator": "=", "value": "in" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "close",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "router",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction", "operator": "=", "value": "out" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Router response",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "responses",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"responses\" and r._field == \"count\" and r.host =~ /${host}/)\n    |> group(columns: [\"status\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipe Throughput (per $resolution)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Pipe Response Time (per $resolution)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Proxy Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Proxy response distribution (per $resolution)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\",\"error\",\"complete\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Proxy Timers (ok)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r.error == \"false\" and r.complete == \"true\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "error", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "true" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "OK Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r.error == \"false\" and r.complete == \"true\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Proxy Timers (incomplete)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r.complete == \"false\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "pipe" },
      { "condition": "AND", "key": "complete", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Incomplete Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"pipe\" and r.host =~ /${host}/ and r.complete == \"false\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backend Throughput (per $resolution)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"backend\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Backend Response Time (per $resolution)",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"backend\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$resolution" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "requests",
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"backend\" and r.host =~ /${host}/)\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "layer", "operator": "=", "value": "backend" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend response distribution (per $resolution)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"count\" and r.layer == \"backend\" and r.host =~ /${host}/ and r._value > 0)\n    |> group(columns: [\"name\",\"error\",\"complete\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Backend Timers (ok)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"backend\" and r.host =~ /${host}/ and r.error == \"false\" and r.complete == \"true\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "OK Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"backend\" and r.host =~ /${host}/ and r.error == \"false\" and r.complete == \"true\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: 1m, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Backend Timers (incomplete)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"backend\" and r.host =~ /${host}/ and r.complete == \"false\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Incomplete Request HeatMap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"requests\" and r._field == \"mean\" and r.layer == \"backend\" and r.host =~ /${host}/ and r.complete == \"false\")\n    |> group(columns: [\"name\"], mode: \"by\")\n    |> aggregateWindow(every: 1m, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"NumGoroutine\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"NumThread\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "CGo Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"NumCgoCall\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "GC Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"service.debug.GCStats.Pause\" and r._field == \"mean\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "GC Spread",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"debug\" and r._field == \"GCStats.NumGC\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"service.runtime.MemStats.PauseNs\" and r._field == \"mean\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Allocated Mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.Alloc\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Sys (bytes obtained from system)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.MSpanSys\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Stack Management",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.StackSys\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Heap Management",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.HeapSys\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Idle Memory",
   "type": "graph",
   "description": "HeapIdle minus HeapReleased estimates the amount of memory that could be returned to the OS, but is being retained by the runtime so it can grow the heap without requesting more memory from the OS. If this difference is significantly larger than the heap size, it indicates there was a recent transient spike in live heap size.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.HeapReleased\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Heap Alloc vs InUse",
   "type": "timeseries",
   "description": "HeapInuse minus HeapAlloc estimates the amount of memory that has been dedicated to particular size classes, but is not currently being used. This is an upper bound on fragmentation, but in general this memory can be reused efficiently.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.HeapAlloc\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    },
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.HeapInuse\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: mean)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Pointer Lookups",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.Lookups\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  },
  {
   "title": "Memory Management",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.Frees\" and r.host =~ /${host}/)\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    },
    {
     "query": "from(bucket: \"krakend\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"runtime\" and r._field == \"MemStats.Mallocs\" and r.host =~ /${host}/)\n    |> group(columns: [\"host\"], mode: \"by\")\n    |> aggregateWindow(every: ${resolution}, fn: sum)\n    |> yield()"
    }
   ]
  }
 ]
}