{
 "title": "KrakenD - Redis",
 "description": "KrakenD dashboard based on Prometheus integration via OpenTelemetry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "app", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(krakend_proxy_duration_bucket,http_route)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,15m,30m,1h,2h,1d" },
   { "name": "max_list", "label": "Max items", "query": "3,5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "Pool config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max connections",
   "type": "stat",
   "description": "The maximum number of open connections allowed",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_max{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max idle connections",
   "type": "stat",
   "description": "The maximum number of idle open connections allowed",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_idle_max{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min idle connections",
   "type": "stat",
   "description": "The minimum number of idle open connections allowed",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_client_connections_idle_min{app=~\"$app\", instance=~\"$instance\", krakend_endpoint_route=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pool overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Connection count",
   "type": "timeseries",
   "description": "The number of connections that are currently in state described by the state attribute",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(state) (avg_over_time(db_client_connections_usage{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "timeseries",
   "description": "The number of connection timeouts that have occurred trying to obtain a connection from the pool",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(changes(db_client_connections_timeouts{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg creation time",
   "type": "timeseries",
   "description": "The time it took to create a new connection.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(db_client_connections_create_time_milliseconds_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg usage time",
   "type": "timeseries",
   "description": "The time between borrowing a connection and returning it to the pool",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(db_client_connections_use_time_milliseconds_count{app=~\"$app\", instance=~\"$instance\", http_route=~\"$endpoint\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}